### ISSUE TITLE
Using with react-native

### ISSUE THREAD

**Issue by fkerekiglobant** [elisherer/react-waterfall-redux-devtools-middleware#2]
The package won't work "as is" with React Native. What needs to be done in order to make it work, possibly with https://github.com/zalmoxisus/remote-redux-devtools ?

**Comment by elisherer** [comment]
@fkerekiglobant 
I'm using web's messages (i.e. postMessage) to mimic redux devtools extension injected client.

I think in order to do what you want, a more aggressive approach needs to be done, like creating an actual redux store which will use the redux devtools, and will listen to actions going through waterfall and,  on the other side, apply time travel actions from redux into waterfall.

This will also put a dependency to the library (which I was trying to avoid, since it is added to the bundle if not used properly)

this would have to be something like 'react-waterfall-remote-redux-devtools-middleware' :smile: , you are welcome to create one!
